version: '0.0.1'

services:
    nginx:
        build: 
            context: ./'Web - Nginx'
            args:
                - user=test
                - pass=test
        image: 'woodytoys/nginx'
    web:
        build: 
            context: ./'Web - NodeJS'
        image: 'woodytoys/web'
        port: '80:80'
        links: db:db
    db:
        build: 
            context: ./'Web - DB'
        image: 'mongo'
        port: '27017:27017'
    dns:
        build:
            context: ./DNS
        image: docker-bind
