version: '2.0'

services:
    dns:
        image: resystit/bind9
        volumes:
            - ./dns/twoinone/etc/bind:/etc/bind
            - ./dns/twoinone/etc/resolv.conf:/etc/resolv.conf
            - ./dns/twoinone/etc/rndc.conf:/etc/rndc.conf
            - ./dns/twoinone/etc/rndc.key:/etc/rndc.key
        ports:
            - 53:53/udp
            - 53:53/tcp
    nginxCloud:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - cloud_engine
        volumes:
            - ./owncloud/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/log/nginx:/var/log/nginx
            - ./owncloud/etc/letsencrypt:/etc/letsencrypt
    cloud_engine:
        image: owncloud:latest  
        expose:
            - "80"
        volumes:
            - ./owncloud/data:/var/www/html/data
            - ./owncloud/config:/var/www/html/config
        links:
            - cloud_db
            - cloud_cache
    cloud_db:
        image: mysql:latest
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: owncloud
            MYSQL_USER: owncloud
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: r00tpassword
        volumes:
            - ./owncloud/mysql:/var/lib/mysql
    cloud_cache:
        image: redis:latest
        expose:
            - "6379"
    asterisk:
        image: matiuso/debisterisk:latest
        ports:
          - 5060:5060/udp
          - 5060:5060/tcp
          - 16384-16394:16384-16394/udp
        volumes: # fichiers intéressants => extensions, sip, users, voicemail
          - ./voip/etc/asterisk/modif/extensions.conf:/etc/asterisk/extensions.conf
          - ./voip/etc/asterisk/modif/sip.conf:/etc/asterisk/sip.conf
          - ./voip/etc/asterisk/modif/users.conf:/etc/asterisk/users.conf
          - ./voip/etc/asterisk/modif/voicemail.conf:/etc/asterisk/voicemail.conf
          - ./voip/etc/asterisk/modif/features.conf:/etc/asterisk/features.conf
          - /etc/localtime:/etc/localtime:ro
