version: '2.0'

services:
    dns:
        image: pstauffer/bind
        volumes:
            - ./dns/etc/bind:/etc/bind
            - ./dns/etc/resolv.conf:/etc/resolv.conf
            - ./dns/var/cache/bind:/var/cache/bind
            - ./dns/var/log/named:/var/log/named
        ports:
            - 53:53/udp
            - 53:53/tcp
    db:
        image: postgres
        environment:
            - POSTGRES_USER = "woodytoys"
            - POSTGRES_PASSWORD = "superwoody"
            - POSTGRES_DB = "woodymarket"
        volumes:
            - ./db/data:/var/lib/postgresql/data
    nginx:
        restart: always
        build:
            context: ./nginx
        image: 'woodytoys/nginx'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./websites/wt4.ephec-ti.be:/var/www/wt4.ephec-ti.be/
            - ./websites/b2b.wt4.ephec-ti.be:/var/www/b2b.wt4.ephec-ti.be
            - ./websites/intranet.wt4.ephec-ti.be:/var/www/intranet.wt4.ephec-ti.be
            - ./nginx/letsencrypt:/etc/letsencrypt/
        links:
            - public:public
            - marketplace:marketplace
            - intranet:intranet
    public:
        image: bitnami/php-fpm
        volumes:
            - "./websites/wt4.ephec-ti.be:/var/www/wt4.ephec-ti.be"
    marketplace:
        image: bitnami/php-fpm
        volumes:
            - "./websites/b2b.wt4.ephec-ti.be:/var/www/b2b.wt4.ephec-ti.be"
        links:
            - db:db
    intranet:
        image: bitnami/php-fpm
        volumes:
            - "./websites/intranet.wt4.ephec-ti.be:/var/www/intranet.wt4.ephec-ti.be"
