version: '2.0'

services:
    dns-externe:
        image: resystit/bind9
        volumes:
            - ./dns/externe/etc/bind:/etc/bind
            #- ./dns/externe/etc/resolv.conf:/etc/resolv.conf
            #- ./dns/var/cache/bind:/var/cache/bind
            #- ./dns/var/log/named:/var/log/named
        ports:
            - 53:53/udp
            - 53:53/tcp
    dns-interne:
        image: resystit/bind9
        volumes:
            - ./dns/interne/etc/bind:/etc/bind
            - ./dns/interne/etc/resolv.conf:/etc/resolv.conf
    mail:
        image: tvial/docker-mailserver:2.1
        hostname: mail
        domainname: wt4.ephec-ti.be.
        ports:
        - 25:25 # smtp
        - 143:143 # imap
        - 587:587 # smtp / ssl
        - 993:993 # imap / ssl
        #- 110:100 # pop3
        #- 995:995 # pop3 / ssl
        volumes:
        - mail/ingoing/emails:/var/mail
        #- mailstate:/var/mail-state
        - ./mail:/tmp/docker-mailserver/
        environment:
        - ENABLE_SPAMASSASSIN=1 # antispam
        - ENABLE_CLAMAV=1 # antivirus
        - ENABLE_FAIL2BAN=1
        - ENABLE_POSTGREY=1 # filtre par liste grise
        #- ENABLE_POP3=1
        - ENABLE_FETCHMAIL=1
        - ONE_DIR=0
        - DMS_DEBUG=1 # env = dev
        - SA_TAG=2.0
        - SA_TAG2=6.31
        #- SSL_TYPE=letsencrypt
        cap_add:
        - NET_ADMIN
