version: '2.0'

services:
    dns:
        build:
            context: ./dns
        image: woodytoys/bind
    db:
        build:
            context: ./db
        image: 'woodytoys/mongo'
    nginx:
        build:
            context: ./nginx
        image: 'woodytoys/nginx'
        ports:
            - 80:80
        links:
            - public:public
            - marketplace:marketplace
            - intranet:intranet
    public:
        build:
            context: ./websites/wt4.ephec-ti.be
        image: 'woodytoys/public'
        ports:
            - 8080:8080
        #volumes:
            #- "./websites/wt4.ephec-ti.be:/var/www/wt4.ephec-ti.be"
        command: node /var/www/wt4.ephec-ti.be/server
    marketplace:
        build:
            context: ./websites/b2b.wt4.ephec-ti.be
        ports:
            - 8080:8080
        image: 'woodytoys/marketplace'
        #volumes:
            #- "./websites/b2b.wt4.ephec-ti.be:/var/www/b2b.wt4.ephec-ti.be"
        links:
            - db:db
        command: node /var/www/b2b.wt4.ephec-ti.be/server
    intranet:
        build:
            context: ./websites/intranet.wt4.ephec-ti.be
        ports:
            - 8080:8080
        image: 'woodytoys/intranet'
        #volumes:
            #- "./websites/intranet.wt4.ephec-ti.be:/var/www/intranet.wt4.ephec-ti.be"
        command: node /var/www/intranet.wt4.ephec-ti.be/server
