version: '2.0'

services:
    dns:
        image: resystit/bind9
        volumes:
            - ./dns/twoinone/etc/bind:/etc/bind
            - ./dns/twoinone/etc/resolv.conf:/etc/resolv.conf
            - ./dns/twoinone/etc/rndc.conf:/etc/rndc.conf
            - ./dns/twoinone/etc/rndc.key:/etc/rndc.key
        ports:
            - 53:53/udp
            - 53:53/tcp
    asterisk:
        image: matiuso/debisterisk:latest
        ports:
          - 5060:5060/udp
          - 5060:5060/tcp
          - 16384-16394:16384-16394/udp
        volumes: # fichiers intéressants => extensions, sip, users, voicemail
          - ./voip/etc/asterisk/modif/extensions.conf:/etc/asterisk/extensions.conf
          - ./voip/etc/asterisk/modif/sip.conf:/etc/asterisk/sip.conf
          - ./voip/etc/asterisk/modif/users.conf:/etc/asterisk/users.conf
          - ./voip/etc/asterisk/modif/voicemail.conf:/etc/asterisk/voicemail.conf
          - /etc/localtime:/etc/localtime:ro
