version: '2.0'

services:
    dns:
        image: resystit/bind9
        volumes:
            - ./dns/twoinone/etc/bind:/etc/bind
            - ./dns/twoinone/etc/resolv.conf:/etc/resolv.conf
            - ./dns/twoinone/etc/rndc.conf:/etc/rndc.conf
            - ./dns/twoinone/etc/rndc.key:/etc/rndc.key
        ports:
            - 53:53/udp
            - 53:53/tcp
    mail:
        image: tvial/docker-mailserver:latest
        hostname: mail
        domainname: wt4.ephec-ti.be
        ports:
          - "25:25"
          - "143:143"
          - "587:587"
          - "993:993"
          - "110:110"
          - "995:995"
        volumes:
          - ./mail/ingoing:/var/mail
          - ./mail/state:/var/mail-state
          - /etc/letsencrypt:/etc/letsencrypt/
          - /etc/localtime:/etc/localtime:ro
          - ./config/:/tmp/docker-mailserver/
        environment:
          - ENABLE_SPAMASSASSIN=1 # antispam
          - ENABLE_CLAMAV=1 # antivirus
          - ENABLE_FAIL2BAN=0
          - ENABLE_POSTGREY=1 # filtre par liste grise
          - ENABLE_FETCHMAIL=1
          - ENABLE_POP3=1
          - ONE_DIR=1
          - DMS_DEBUG=0 # 1: env = dev
          - SA_TAG=2.0
          - SA_TAG2=6.31
          - SASL_PASSWD="lol"
          - SSL_TYPE=letsencrypt
